caraml:
  registry:
    # Whether to create/update streaming ingestion jobs on feature table creation/update
    syncIngestionJobOnSpecUpdate: true

  kubernetes:
    # Whether to use in-cluster Kubernetes configuration or default kube config.
    inCluster: false

  monitoring:
    # Configure the behaviour of the timer metrics
    timer:
      # Published percentiles
      percentiles:
        - 0.5
        - 0.95
        - 0.99
      # Minimum expected latency
      minBucketMs: 1
      # Maximum expected latency
      maxBucketMs: 200

  # SparkApplicationSpec for ingestion and historical retrieval jobs. Refer to the official Spark Operator documentation
  # for the full range of options supported. Feature schema and source information will be appended to existing arguments
  # as the flag arguments --feature-table and --store. For batch ingestion jobs, --start-time and --end-time will be added
  # to indicate the range of data to be ingested.
  jobService:
    streamIngestion:
      - store: store-name
        namespace: spark-operator
        # Stream ingestion spark application spec
        # sparkApplicationSpec:
    batchIngestion:
      - store: store-name
        namespace: spark-operator
        # Batch ingestion spark application spec
        # sparkApplicationSpec:
    historicalRetrieval:
      namespace: spark-operator
      # Historical retrieval job spark application spec
      # sparkApplicationSpec:


grpc:
  server:
    port: 6565

spring:
  jpa:
    properties.hibernate:
      format_sql: true
      event:
        merge:
          entity_copy_observer: allow
    hibernate.naming.physical-strategy=org.hibernate.boot.model.naming: PhysicalNamingStrategyStandardImpl
    hibernate.ddl-auto: validate
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_DATABASE:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  flyway:
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
    metrics:
      enabled: true
