apiVersion: v1
kind: Secret
metadata:
  name: {{ template "caraml-store-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "caraml-store-registry.name" . }}
    component: registry
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  application-secret.yaml: |
{{- toYaml (index .Values "application-secret.yaml") | nindent 4  }}
