name: CaraML Store CI

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Linting
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Build Image
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
        with:
          arguments: jib
