name: CaraML Store Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Image
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
        with:
          arguments: jib
      - name: Delete old pre-released packages except for feature branch snapshots
        uses: actions/delete-package-versions@v3
        package-name: 'caraml-store-registry'
        min-versions-to-keep: 2
        ignore-versions: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$,.+-snapshot$'